/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class loading extends javax.swing.JFrame {

    /**
     * Creates new form loading
     */
    public loading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        progcount = new javax.swing.JProgressBar();
        percount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("WORD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 50));

        jLabel2.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("QUEST");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 150, -1));
        jPanel1.add(progcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 690, 20));

        percount.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        percount.setForeground(new java.awt.Color(255, 153, 0));
        percount.setText("%");
        jPanel1.add(percount, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 60, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/loading.jpeg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 400));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        loading load = new loading();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                load.show();
            }
        });
        try{
            for(int k=0; k<=100; k++){
                Thread.sleep(50);
                load.progcount.setValue(k);
                load.percount.setText(Integer.toString(k)+"%");   
    }
        }catch(Exception e){
            
    }
         name mnu = new name();
        load.show(false);
        mnu.show(true);
        
        load.dispose();
    }
        
        
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel percount;
    private javax.swing.JProgressBar progcount;
    // End of variables declaration//GEN-END:variables
}
