
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class start4 extends javax.swing.JFrame {

       private boolean hintUsed = false;
    public start4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        iconbar = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        closebtn = new javax.swing.JLabel();
        max = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        linemenu = new javax.swing.JPanel();
        linesetting = new javax.swing.JPanel();
        menu1 = new javax.swing.JPanel();
        mnubtn = new javax.swing.JLabel();
        setting = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        linehint = new javax.swing.JPanel();
        hint = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JTABPANE = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        no2 = new javax.swing.JPanel();
        btns1 = new javax.swing.JButton();
        btns2 = new javax.swing.JButton();
        btns3 = new javax.swing.JButton();
        btns4 = new javax.swing.JButton();
        btns5 = new javax.swing.JButton();
        btns6 = new javax.swing.JButton();
        btns7 = new javax.swing.JButton();
        btns8 = new javax.swing.JButton();
        btns9 = new javax.swing.JButton();
        btns10 = new javax.swing.JButton();
        btns11 = new javax.swing.JButton();
        btns12 = new javax.swing.JButton();
        btns13 = new javax.swing.JButton();
        btns14 = new javax.swing.JButton();
        btns15 = new javax.swing.JButton();
        btns16 = new javax.swing.JButton();
        btns17 = new javax.swing.JButton();
        btns18 = new javax.swing.JButton();
        btns19 = new javax.swing.JButton();
        btns20 = new javax.swing.JButton();
        btns21 = new javax.swing.JButton();
        btns22 = new javax.swing.JButton();
        btns23 = new javax.swing.JButton();
        bnk13 = new javax.swing.JTextField();
        bnk14 = new javax.swing.JTextField();
        bnk15 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bnk16 = new javax.swing.JTextField();
        bs6 = new javax.swing.JLabel();
        bt88 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        no4 = new javax.swing.JPanel();
        btn30 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn37 = new javax.swing.JButton();
        btn38 = new javax.swing.JButton();
        btn39 = new javax.swing.JButton();
        btn40 = new javax.swing.JButton();
        btn41 = new javax.swing.JButton();
        btn42 = new javax.swing.JButton();
        btn43 = new javax.swing.JButton();
        btn44 = new javax.swing.JButton();
        btn45 = new javax.swing.JButton();
        btn46 = new javax.swing.JButton();
        btn47 = new javax.swing.JButton();
        btn48 = new javax.swing.JButton();
        btn49 = new javax.swing.JButton();
        btn50 = new javax.swing.JButton();
        btn51 = new javax.swing.JButton();
        btn52 = new javax.swing.JButton();
        bnk25 = new javax.swing.JTextField();
        bnk26 = new javax.swing.JTextField();
        bnk27 = new javax.swing.JTextField();
        bnk28 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bs5 = new javax.swing.JLabel();
        bt89 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(51, 51, 51));
        header.setPreferredSize(new java.awt.Dimension(820, 35));
        header.setLayout(new java.awt.BorderLayout());

        iconbar.setBackground(new java.awt.Color(51, 51, 51));
        iconbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(51, 51, 51));
        close.setLayout(new java.awt.BorderLayout());

        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/close (2).png"))); // NOI18N
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closebtnMouseExited(evt);
            }
        });
        close.add(closebtn, java.awt.BorderLayout.CENTER);

        iconbar.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        max.setBackground(new java.awt.Color(51, 51, 51));
        max.setLayout(new java.awt.BorderLayout());
        iconbar.add(max, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        header.add(iconbar, java.awt.BorderLayout.LINE_END);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(35, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linemenu.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout linemenuLayout = new javax.swing.GroupLayout(linemenu);
        linemenu.setLayout(linemenuLayout);
        linemenuLayout.setHorizontalGroup(
            linemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        linemenuLayout.setVerticalGroup(
            linemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(linemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 3));

        linesetting.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout linesettingLayout = new javax.swing.GroupLayout(linesetting);
        linesetting.setLayout(linesettingLayout);
        linesettingLayout.setHorizontalGroup(
            linesettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        linesettingLayout.setVerticalGroup(
            linesettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(linesetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, 35, 3));

        menu1.setBackground(new java.awt.Color(51, 51, 51));
        menu1.setLayout(new java.awt.BorderLayout());

        mnubtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/open-menu (3).png"))); // NOI18N
        mnubtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnubtnMouseClicked(evt);
            }
        });
        menu1.add(mnubtn, java.awt.BorderLayout.CENTER);

        jPanel1.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 35, 40));

        setting.setBackground(new java.awt.Color(51, 51, 51));
        setting.setLayout(new java.awt.BorderLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/icons8-back-35.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        setting.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 35, 40));

        linehint.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout linehintLayout = new javax.swing.GroupLayout(linehint);
        linehint.setLayout(linehintLayout);
        linehintLayout.setHorizontalGroup(
            linehintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        linehintLayout.setVerticalGroup(
            linehintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(linehint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 35, 3));

        hint.setBackground(new java.awt.Color(51, 51, 51));
        hint.setLayout(new java.awt.BorderLayout());
        jPanel1.add(hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 35, 40));

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        no2.setPreferredSize(new java.awt.Dimension(720, 318));
        no2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btns1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns1.setText("S");
        btns1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns1MouseExited(evt);
            }
        });
        no2.add(btns1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 254, 45, 35));

        btns2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns2.setText("A");
        btns2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns2MouseExited(evt);
            }
        });
        no2.add(btns2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 254, 45, 35));

        btns3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns3.setText("T");
        btns3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns3MouseExited(evt);
            }
        });
        no2.add(btns3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 254, 45, 35));

        btns4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns4.setText("H");
        btns4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns4MouseExited(evt);
            }
        });
        no2.add(btns4, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 254, 45, 35));

        btns5.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns5.setText("O");
        btns5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns5MouseExited(evt);
            }
        });
        no2.add(btns5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 254, 45, 35));

        btns6.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns6.setText("X");
        btns6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns6MouseExited(evt);
            }
        });
        no2.add(btns6, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 254, 45, 35));

        btns7.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns7.setText("I");
        btns7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns7MouseExited(evt);
            }
        });
        no2.add(btns7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 254, 45, 35));

        btns8.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns8.setText("E");
        btns8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns8MouseExited(evt);
            }
        });
        no2.add(btns8, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 254, 45, 35));

        btns9.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns9.setText("L");
        btns9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns9MouseExited(evt);
            }
        });
        btns9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns9ActionPerformed(evt);
            }
        });
        no2.add(btns9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 254, 45, 35));

        btns10.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns10.setText("R");
        btns10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns10MouseExited(evt);
            }
        });
        no2.add(btns10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 45, 35));

        btns11.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns11.setText("C");
        btns11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns11MouseExited(evt);
            }
        });
        no2.add(btns11, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 294, 45, 35));

        btns12.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns12.setText("N");
        btns12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns12MouseExited(evt);
            }
        });
        no2.add(btns12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 294, 45, 35));

        btns13.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns13.setText("K");
        btns13.setToolTipText("");
        btns13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns13MouseExited(evt);
            }
        });
        no2.add(btns13, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 294, 45, 35));

        btns14.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns14.setText("1");
        btns14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns14MouseExited(evt);
            }
        });
        no2.add(btns14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 294, 45, 35));

        btns15.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns15.setText("2");
        btns15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns15MouseExited(evt);
            }
        });
        no2.add(btns15, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 294, 45, 35));

        btns16.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns16.setText("3");
        btns16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns16MouseExited(evt);
            }
        });
        no2.add(btns16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 294, 45, 35));

        btns17.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns17.setText("4");
        btns17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns17MouseExited(evt);
            }
        });
        no2.add(btns17, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 294, 45, 35));

        btns18.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns18.setText("5");
        btns18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns18MouseExited(evt);
            }
        });
        no2.add(btns18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 45, 35));

        btns19.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns19.setText("6");
        btns19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns19MouseExited(evt);
            }
        });
        no2.add(btns19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 45, 35));

        btns20.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns20.setText("7");
        btns20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns20MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns20MouseExited(evt);
            }
        });
        no2.add(btns20, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 330, 45, 35));

        btns21.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns21.setText("8");
        btns21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns21MouseExited(evt);
            }
        });
        no2.add(btns21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 45, 35));

        btns22.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns22.setText("9");
        btns22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns22MouseExited(evt);
            }
        });
        no2.add(btns22, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 330, 45, 35));

        btns23.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btns23.setText("0");
        btns23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btns23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btns23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btns23MouseExited(evt);
            }
        });
        no2.add(btns23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 45, 35));

        bnk13.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        no2.add(bnk13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 44, 35));

        bnk14.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        no2.add(bnk14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 44, 35));

        bnk15.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        no2.add(bnk15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 44, 35));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("An order, mutable collection of items");
        no2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 480, 38));

        bnk16.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        no2.add(bnk16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 44, 35));

        bs6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/bulb (3) (1).png"))); // NOI18N
        bs6.setOpaque(true);
        bs6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bs6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bs6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bs6MouseExited(evt);
            }
        });
        no2.add(bs6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 40));

        bt88.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        bt88.setText("SUBMIT");
        bt88.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt88MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt88MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt88MouseExited(evt);
            }
        });
        no2.add(bt88, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 100, 40));

        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/back (1).png"))); // NOI18N
        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b6MouseExited(evt);
            }
        });
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        no2.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/462558248_2258794291165504_1467247230088445982_n (1).jpg"))); // NOI18N
        no2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 430));

        jPanel4.add(no2, java.awt.BorderLayout.CENTER);

        JTABPANE.addTab("tab2", jPanel4);

        jPanel6.setLayout(new java.awt.BorderLayout());

        no4.setPreferredSize(new java.awt.Dimension(720, 318));
        no4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn30.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn30.setText("V");
        btn30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn30MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn30MouseExited(evt);
            }
        });
        no4.add(btn30, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 254, 45, 35));

        btn31.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn31.setText("C");
        btn31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn31MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn31MouseExited(evt);
            }
        });
        no4.add(btn31, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 254, 45, 35));

        btn32.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn32.setText("U");
        btn32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn32MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn32MouseExited(evt);
            }
        });
        no4.add(btn32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 254, 45, 35));

        btn33.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn33.setText("T");
        btn33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn33MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn33MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn33MouseExited(evt);
            }
        });
        no4.add(btn33, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 254, 45, 35));

        btn34.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn34.setText("N");
        btn34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn34MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn34MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn34MouseExited(evt);
            }
        });
        no4.add(btn34, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 254, 45, 35));

        btn35.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn35.setText("J");
        btn35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn35MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn35MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn35MouseExited(evt);
            }
        });
        no4.add(btn35, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 254, 45, 35));

        btn36.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn36.setText("P");
        btn36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn36MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn36MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn36MouseExited(evt);
            }
        });
        no4.add(btn36, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 254, 45, 35));

        btn37.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn37.setText("I");
        btn37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn37MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn37MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn37MouseExited(evt);
            }
        });
        no4.add(btn37, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 254, 45, 35));

        btn38.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn38.setText("A");
        btn38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn38MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn38MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn38MouseExited(evt);
            }
        });
        btn38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn38ActionPerformed(evt);
            }
        });
        no4.add(btn38, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 254, 45, 35));

        btn39.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn39.setText("O");
        btn39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn39MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn39MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn39MouseExited(evt);
            }
        });
        no4.add(btn39, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 45, 35));

        btn40.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn40.setText("E");
        btn40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn40MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn40MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn40MouseExited(evt);
            }
        });
        no4.add(btn40, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 294, 45, 35));

        btn41.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn41.setText("H");
        btn41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn41MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn41MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn41MouseExited(evt);
            }
        });
        no4.add(btn41, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 294, 45, 35));

        btn42.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn42.setText("L");
        btn42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn42MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn42MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn42MouseExited(evt);
            }
        });
        no4.add(btn42, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 294, 45, 35));

        btn43.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn43.setText("1");
        btn43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn43MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn43MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn43MouseExited(evt);
            }
        });
        no4.add(btn43, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 294, 45, 35));

        btn44.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn44.setText("2");
        btn44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn44MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn44MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn44MouseExited(evt);
            }
        });
        no4.add(btn44, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 294, 45, 35));

        btn45.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn45.setText("3");
        btn45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn45MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn45MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn45MouseExited(evt);
            }
        });
        no4.add(btn45, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 294, 45, 35));

        btn46.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn46.setText("4");
        btn46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn46MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn46MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn46MouseExited(evt);
            }
        });
        no4.add(btn46, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 294, 45, 35));

        btn47.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn47.setText("5");
        btn47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn47MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn47MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn47MouseExited(evt);
            }
        });
        btn47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn47ActionPerformed(evt);
            }
        });
        no4.add(btn47, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 45, 35));

        btn48.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn48.setText("6");
        btn48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn48MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn48MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn48MouseExited(evt);
            }
        });
        no4.add(btn48, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 45, 35));

        btn49.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn49.setText("7");
        btn49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn49MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn49MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn49MouseExited(evt);
            }
        });
        no4.add(btn49, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 330, 45, 35));

        btn50.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn50.setText("8");
        btn50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn50MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn50MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn50MouseExited(evt);
            }
        });
        no4.add(btn50, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 45, 35));

        btn51.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn51.setText("9");
        btn51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn51MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn51MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn51MouseExited(evt);
            }
        });
        no4.add(btn51, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 330, 45, 35));

        btn52.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btn52.setText("0");
        btn52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn52MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn52MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn52MouseExited(evt);
            }
        });
        no4.add(btn52, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 45, 35));

        bnk25.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        no4.add(bnk25, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 44, 35));

        bnk26.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        no4.add(bnk26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 44, 35));

        bnk27.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        no4.add(bnk27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 44, 35));

        bnk28.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        no4.add(bnk28, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 44, 35));

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Used to repeat a block of code");
        no4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 470, 30));

        bs5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/bulb (3) (1).png"))); // NOI18N
        bs5.setOpaque(true);
        bs5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bs5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bs5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bs5MouseExited(evt);
            }
        });
        no4.add(bs5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 40));

        bt89.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        bt89.setText("SUBMIT");
        bt89.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt89MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt89MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt89MouseExited(evt);
            }
        });
        bt89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt89ActionPerformed(evt);
            }
        });
        no4.add(bt89, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 100, 40));

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/back (1).png"))); // NOI18N
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b5MouseExited(evt);
            }
        });
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        no4.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/462558248_2258794291165504_1467247230088445982_n (1).jpg"))); // NOI18N
        no4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 430));

        jPanel6.add(no4, java.awt.BorderLayout.CENTER);

        JTABPANE.addTab("tab4", jPanel6);

        jPanel2.add(JTABPANE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -41, 802, 460));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void changecolor (JLabel hover, Color rand){
        hover.setBackground(rand);
    }

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closebtnMouseClicked

    private void closebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseEntered
        changecolor(closebtn, new Color(255,0,0));
    }//GEN-LAST:event_closebtnMouseEntered

    private void closebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseExited
        changecolor(closebtn, new Color(255,0,0));
    }//GEN-LAST:event_closebtnMouseExited

    private void mnubtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnubtnMouseClicked
        menu mn = new menu();
        mn.show();

        dispose();
    }//GEN-LAST:event_mnubtnMouseClicked

    public void backcolor (JButton hover, Color rand){
        hover.setBackground(rand);
    }
    
    private void btn30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn30MouseClicked
        fillBlankSpace3("V");
    }//GEN-LAST:event_btn30MouseClicked

    private void btn30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn30MouseEntered
        backcolor (btn30, new Color(153,255,153));
    }//GEN-LAST:event_btn30MouseEntered

    private void btn30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn30MouseExited
        backcolor (btn30, new Color(255,255,255));
    }//GEN-LAST:event_btn30MouseExited

    private void btn31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn31MouseClicked
        fillBlankSpace3("C");
    }//GEN-LAST:event_btn31MouseClicked

    private void btn31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn31MouseEntered
        backcolor (btn31, new Color(153,255,153));
    }//GEN-LAST:event_btn31MouseEntered

    private void btn31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn31MouseExited
        backcolor (btn31, new Color(255,255,255));
    }//GEN-LAST:event_btn31MouseExited

    private void btn32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn32MouseClicked
        fillBlankSpace3("U");
    }//GEN-LAST:event_btn32MouseClicked

    private void btn32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn32MouseEntered
        backcolor (btn32, new Color(153,255,153));
    }//GEN-LAST:event_btn32MouseEntered

    private void btn32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn32MouseExited
        backcolor (btn32, new Color(255,255,255));
    }//GEN-LAST:event_btn32MouseExited

    private void btn33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn33MouseClicked
        fillBlankSpace3("T");
    }//GEN-LAST:event_btn33MouseClicked

    private void btn33MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn33MouseEntered
        backcolor (btn33, new Color(153,255,153));
    }//GEN-LAST:event_btn33MouseEntered

    private void btn33MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn33MouseExited
        backcolor (btn33, new Color(255,255,255));
    }//GEN-LAST:event_btn33MouseExited

    private void btn34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn34MouseClicked
        fillBlankSpace3("N");
    }//GEN-LAST:event_btn34MouseClicked

    private void btn34MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn34MouseEntered
        backcolor (btn34, new Color(153,255,153));
    }//GEN-LAST:event_btn34MouseEntered

    private void btn34MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn34MouseExited
        backcolor (btn34, new Color(255,255,255));
    }//GEN-LAST:event_btn34MouseExited

    private void btn35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn35MouseClicked
        fillBlankSpace3("J");
    }//GEN-LAST:event_btn35MouseClicked

    private void btn35MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn35MouseEntered
        backcolor (btn35, new Color(153,255,153));
    }//GEN-LAST:event_btn35MouseEntered

    private void btn35MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn35MouseExited
        backcolor (btn35, new Color(255,255,255));
    }//GEN-LAST:event_btn35MouseExited

    private void btn36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn36MouseClicked
        fillBlankSpace3("P");
    }//GEN-LAST:event_btn36MouseClicked

    private void btn36MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn36MouseEntered
        backcolor (btn36, new Color(153,255,153));
    }//GEN-LAST:event_btn36MouseEntered

    private void btn36MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn36MouseExited
        backcolor (btn36, new Color(255,255,255));
    }//GEN-LAST:event_btn36MouseExited

    private void btn37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn37MouseClicked
        fillBlankSpace3("I");
    }//GEN-LAST:event_btn37MouseClicked

    private void btn37MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn37MouseEntered
        backcolor (btn37, new Color(153,255,153));
    }//GEN-LAST:event_btn37MouseEntered

    private void btn37MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn37MouseExited
        backcolor (btn37, new Color(255,255,255));
    }//GEN-LAST:event_btn37MouseExited

    private void btn38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn38MouseClicked
        fillBlankSpace3("A");
    }//GEN-LAST:event_btn38MouseClicked

    private void btn38MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn38MouseEntered
        backcolor (btn38, new Color(153,255,153));
    }//GEN-LAST:event_btn38MouseEntered

    private void btn38MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn38MouseExited
        backcolor (btn38, new Color(255,255,255));
    }//GEN-LAST:event_btn38MouseExited

    private void btn38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn38ActionPerformed

    private void btn39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn39MouseClicked
        fillBlankSpace3("O");
    }//GEN-LAST:event_btn39MouseClicked

    private void btn39MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn39MouseEntered
        backcolor (btn39, new Color(153,255,153));
    }//GEN-LAST:event_btn39MouseEntered

    private void btn39MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn39MouseExited
        backcolor (btn39, new Color(255,255,255));
    }//GEN-LAST:event_btn39MouseExited

    private void btn40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn40MouseClicked
        fillBlankSpace3("E");
    }//GEN-LAST:event_btn40MouseClicked

    private void btn40MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn40MouseEntered
        backcolor (btn40, new Color(153,255,153));
    }//GEN-LAST:event_btn40MouseEntered

    private void btn40MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn40MouseExited
        backcolor (btn40, new Color(255,255,255));
    }//GEN-LAST:event_btn40MouseExited

    private void btn41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn41MouseClicked
        fillBlankSpace3("H");
    }//GEN-LAST:event_btn41MouseClicked

    private void btn41MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn41MouseEntered
        backcolor (btn41, new Color(153,255,153));
    }//GEN-LAST:event_btn41MouseEntered

    private void btn41MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn41MouseExited
        backcolor (btn41, new Color(255,255,255));
    }//GEN-LAST:event_btn41MouseExited

    private void btn42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn42MouseClicked
        fillBlankSpace3("L");
    }//GEN-LAST:event_btn42MouseClicked

    private void btn42MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn42MouseEntered
        backcolor (btn42, new Color(153,255,153));
    }//GEN-LAST:event_btn42MouseEntered

    private void btn42MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn42MouseExited
        backcolor (btn42, new Color(255,255,255));
    }//GEN-LAST:event_btn42MouseExited

    private void btn43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn43MouseClicked
        fillBlankSpace3("1");
    }//GEN-LAST:event_btn43MouseClicked

    private void btn43MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn43MouseEntered
        backcolor (btn43, new Color(153,255,153));
    }//GEN-LAST:event_btn43MouseEntered

    private void btn43MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn43MouseExited
        backcolor (btn43, new Color(255,255,255));
    }//GEN-LAST:event_btn43MouseExited

    private void btn44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn44MouseClicked
        fillBlankSpace3("2");
    }//GEN-LAST:event_btn44MouseClicked

    private void btn44MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn44MouseEntered
        backcolor (btn44, new Color(153,255,153));
    }//GEN-LAST:event_btn44MouseEntered

    private void btn44MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn44MouseExited
        backcolor (btn44, new Color(255,255,255));
    }//GEN-LAST:event_btn44MouseExited

    private void btn45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn45MouseClicked
        fillBlankSpace3("3");
    }//GEN-LAST:event_btn45MouseClicked

    private void btn45MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn45MouseEntered
        backcolor (btn45, new Color(153,255,153));
    }//GEN-LAST:event_btn45MouseEntered

    private void btn45MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn45MouseExited
        backcolor (btn45, new Color(255,255,255));
    }//GEN-LAST:event_btn45MouseExited

    private void btn46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn46MouseClicked
        fillBlankSpace3("4");
    }//GEN-LAST:event_btn46MouseClicked

    private void btn46MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn46MouseEntered
        backcolor (btn46, new Color(153,255,153));
    }//GEN-LAST:event_btn46MouseEntered

    private void btn46MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn46MouseExited
        backcolor (btn46, new Color(255,255,255));
    }//GEN-LAST:event_btn46MouseExited

    private void btn47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn47MouseClicked
        fillBlankSpace3("5");
    }//GEN-LAST:event_btn47MouseClicked

    private void btn47MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn47MouseEntered
        backcolor (btn47, new Color(153,255,153));
    }//GEN-LAST:event_btn47MouseEntered

    private void btn47MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn47MouseExited
        backcolor (btn47, new Color(255,255,255));
    }//GEN-LAST:event_btn47MouseExited

    private void btn47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn47ActionPerformed

    private void btn48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn48MouseClicked
        fillBlankSpace3("6");
    }//GEN-LAST:event_btn48MouseClicked

    private void btn48MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn48MouseEntered
        backcolor (btn48, new Color(153,255,153));
    }//GEN-LAST:event_btn48MouseEntered

    private void btn48MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn48MouseExited
        backcolor (btn48, new Color(255,255,255));
    }//GEN-LAST:event_btn48MouseExited

    private void btn49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn49MouseClicked
        fillBlankSpace3("7");
    }//GEN-LAST:event_btn49MouseClicked

    private void btn49MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn49MouseEntered
        backcolor (btn49, new Color(153,255,153));
    }//GEN-LAST:event_btn49MouseEntered

    private void btn49MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn49MouseExited
        backcolor (btn49, new Color(255,255,255));
    }//GEN-LAST:event_btn49MouseExited

    private void btn50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn50MouseClicked
        fillBlankSpace3("8");
    }//GEN-LAST:event_btn50MouseClicked

    private void btn50MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn50MouseEntered
        backcolor (btn50, new Color(153,255,153));
    }//GEN-LAST:event_btn50MouseEntered

    private void btn50MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn50MouseExited
        backcolor (btn50, new Color(255,255,255));
    }//GEN-LAST:event_btn50MouseExited

    private void btn51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn51MouseClicked
        fillBlankSpace3("9");
    }//GEN-LAST:event_btn51MouseClicked

    private void btn51MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn51MouseEntered
        backcolor (btn51, new Color(153,255,153));
    }//GEN-LAST:event_btn51MouseEntered

    private void btn51MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn51MouseExited
        backcolor (btn51, new Color(255,255,255));
    }//GEN-LAST:event_btn51MouseExited

    private void btn52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn52MouseClicked
        fillBlankSpace3("0");
    }//GEN-LAST:event_btn52MouseClicked

    private void btn52MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn52MouseEntered
        backcolor (btn52, new Color(153,255,153));
    }//GEN-LAST:event_btn52MouseEntered

    private void btn52MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn52MouseExited
        backcolor (btn52, new Color(255,255,255));
    }//GEN-LAST:event_btn52MouseExited

    private void btns23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns23MouseExited
        backcolor (btns23, new Color(255,255,255));
    }//GEN-LAST:event_btns23MouseExited

    private void btns23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns23MouseEntered
        backcolor (btns23, new Color(153,255,153));
    }//GEN-LAST:event_btns23MouseEntered

    private void btns23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns23MouseClicked
        fillBlankSpace1("0");
    }//GEN-LAST:event_btns23MouseClicked

    private void btns22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns22MouseExited
        backcolor (btns22, new Color(255,255,255));
    }//GEN-LAST:event_btns22MouseExited

    private void btns22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns22MouseEntered
        backcolor (btns22, new Color(153,255,153));
    }//GEN-LAST:event_btns22MouseEntered

    private void btns22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns22MouseClicked
        fillBlankSpace1("9");
    }//GEN-LAST:event_btns22MouseClicked

    private void btns21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns21MouseExited
        backcolor (btns21, new Color(255,255,255));
    }//GEN-LAST:event_btns21MouseExited

    private void btns21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns21MouseEntered
        backcolor (btns21, new Color(153,255,153));
    }//GEN-LAST:event_btns21MouseEntered

    private void btns21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns21MouseClicked
        fillBlankSpace1("8");
    }//GEN-LAST:event_btns21MouseClicked

    private void btns20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns20MouseExited
        backcolor (btns20, new Color(255,255,255));
    }//GEN-LAST:event_btns20MouseExited

    private void btns20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns20MouseEntered
        backcolor (btns20, new Color(153,255,153));
    }//GEN-LAST:event_btns20MouseEntered

    private void btns20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns20MouseClicked
        fillBlankSpace1("7");
    }//GEN-LAST:event_btns20MouseClicked

    private void btns19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns19MouseExited
        backcolor (btns19, new Color(255,255,255));
    }//GEN-LAST:event_btns19MouseExited

    private void btns19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns19MouseEntered
        backcolor (btns19, new Color(153,255,153));
    }//GEN-LAST:event_btns19MouseEntered

    private void btns19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns19MouseClicked
        fillBlankSpace1("6");
    }//GEN-LAST:event_btns19MouseClicked

    private void btns18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns18MouseExited
        backcolor (btns18, new Color(255,255,255));
    }//GEN-LAST:event_btns18MouseExited

    private void btns18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns18MouseEntered
        backcolor (btns18, new Color(153,255,153));
    }//GEN-LAST:event_btns18MouseEntered

    private void btns18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns18MouseClicked
        fillBlankSpace1("5");
    }//GEN-LAST:event_btns18MouseClicked

    private void btns17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns17MouseExited
        backcolor (btns17, new Color(255,255,255));
    }//GEN-LAST:event_btns17MouseExited

    private void btns17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns17MouseEntered
        backcolor (btns17, new Color(153,255,153));
    }//GEN-LAST:event_btns17MouseEntered

    private void btns17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns17MouseClicked
        fillBlankSpace1("4");
    }//GEN-LAST:event_btns17MouseClicked

    private void btns16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns16MouseExited
        backcolor (btns16, new Color(255,255,255));
    }//GEN-LAST:event_btns16MouseExited

    private void btns16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns16MouseEntered
        backcolor (btns16, new Color(153,255,153));
    }//GEN-LAST:event_btns16MouseEntered

    private void btns16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns16MouseClicked
        fillBlankSpace1("3");
    }//GEN-LAST:event_btns16MouseClicked

    private void btns15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns15MouseExited
        backcolor (btns15, new Color(255,255,255));
    }//GEN-LAST:event_btns15MouseExited

    private void btns15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns15MouseEntered
        backcolor (btns15, new Color(153,255,153));
    }//GEN-LAST:event_btns15MouseEntered

    private void btns15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns15MouseClicked
        fillBlankSpace1("2");
    }//GEN-LAST:event_btns15MouseClicked

    private void btns14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns14MouseExited
        backcolor (btns14, new Color(255,255,255));
    }//GEN-LAST:event_btns14MouseExited

    private void btns14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns14MouseEntered
        backcolor (btns14, new Color(153,255,153));
    }//GEN-LAST:event_btns14MouseEntered

    private void btns14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns14MouseClicked
        fillBlankSpace1("1");
    }//GEN-LAST:event_btns14MouseClicked

    private void btns13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns13MouseExited
        backcolor (btns13, new Color(255,255,255));
    }//GEN-LAST:event_btns13MouseExited

    private void btns13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns13MouseEntered
        backcolor (btns13, new Color(153,255,153));
    }//GEN-LAST:event_btns13MouseEntered

    private void btns13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns13MouseClicked
        fillBlankSpace1("K");
    }//GEN-LAST:event_btns13MouseClicked

    private void btns12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns12MouseExited
        backcolor (btns12, new Color(255,255,255));
    }//GEN-LAST:event_btns12MouseExited

    private void btns12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns12MouseEntered
        backcolor (btns12, new Color(153,255,153));
    }//GEN-LAST:event_btns12MouseEntered

    private void btns12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns12MouseClicked
        fillBlankSpace1("N");
    }//GEN-LAST:event_btns12MouseClicked

    private void btns11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns11MouseExited
        backcolor (btns11, new Color(255,255,255));
    }//GEN-LAST:event_btns11MouseExited

    private void btns11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns11MouseEntered
        backcolor (btns11, new Color(153,255,153));
    }//GEN-LAST:event_btns11MouseEntered

    private void btns11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns11MouseClicked
        fillBlankSpace1("C");
    }//GEN-LAST:event_btns11MouseClicked

    private void btns10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns10MouseExited
        backcolor (btns10, new Color(255,255,255));
    }//GEN-LAST:event_btns10MouseExited

    private void btns10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns10MouseEntered
        backcolor (btns10, new Color(153,255,153));
    }//GEN-LAST:event_btns10MouseEntered

    private void btns10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns10MouseClicked
        fillBlankSpace1("R");
    }//GEN-LAST:event_btns10MouseClicked

    private void btns9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns9ActionPerformed

    private void btns9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns9MouseExited
        backcolor (btns9, new Color(255,255,255));
    }//GEN-LAST:event_btns9MouseExited

    private void btns9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns9MouseEntered
        backcolor (btns9, new Color(153,255,153));
    }//GEN-LAST:event_btns9MouseEntered

    private void btns9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns9MouseClicked
        fillBlankSpace1("L");
    }//GEN-LAST:event_btns9MouseClicked

    private void btns8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns8MouseExited
        backcolor (btns8, new Color(255,255,255));
    }//GEN-LAST:event_btns8MouseExited

    private void btns8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns8MouseEntered
        backcolor (btns8, new Color(153,255,153));
    }//GEN-LAST:event_btns8MouseEntered

    private void btns8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns8MouseClicked
        fillBlankSpace1("E");
    }//GEN-LAST:event_btns8MouseClicked

    private void btns7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns7MouseExited
        backcolor (btns7, new Color(255,255,255));
    }//GEN-LAST:event_btns7MouseExited

    private void btns7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns7MouseEntered
        backcolor (btns7, new Color(153,255,153));
    }//GEN-LAST:event_btns7MouseEntered

    private void btns7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns7MouseClicked
        fillBlankSpace1("I");
    }//GEN-LAST:event_btns7MouseClicked

    private void btns6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns6MouseExited
        backcolor (btns6, new Color(255,255,255));
    }//GEN-LAST:event_btns6MouseExited

    private void btns6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns6MouseEntered
        backcolor (btns6, new Color(153,255,153));
    }//GEN-LAST:event_btns6MouseEntered

    private void btns6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns6MouseClicked
        fillBlankSpace1("X");
    }//GEN-LAST:event_btns6MouseClicked

    private void btns5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns5MouseExited
        backcolor (btns5, new Color(255,255,255));
    }//GEN-LAST:event_btns5MouseExited

    private void btns5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns5MouseEntered
        backcolor (btns5, new Color(153,255,153));
    }//GEN-LAST:event_btns5MouseEntered

    private void btns5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns5MouseClicked
        fillBlankSpace1("O");
    }//GEN-LAST:event_btns5MouseClicked

    private void btns4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns4MouseExited
        backcolor (btns4, new Color(255,255,255));
    }//GEN-LAST:event_btns4MouseExited

    private void btns4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns4MouseEntered
        backcolor (btns4, new Color(153,255,153));
    }//GEN-LAST:event_btns4MouseEntered

    private void btns4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns4MouseClicked
        fillBlankSpace1("H");
    }//GEN-LAST:event_btns4MouseClicked

    private void btns3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns3MouseExited
        backcolor (btns3, new Color(255,255,255));
    }//GEN-LAST:event_btns3MouseExited

    private void btns3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns3MouseEntered
        backcolor (btns3, new Color(153,255,153));
    }//GEN-LAST:event_btns3MouseEntered

    private void btns3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns3MouseClicked
        fillBlankSpace1("T");
    }//GEN-LAST:event_btns3MouseClicked

    private void btns2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns2MouseExited
        backcolor (btns2, new Color(255,255,255));
    }//GEN-LAST:event_btns2MouseExited

    private void btns2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns2MouseEntered
        backcolor (btns2, new Color(153,255,153));
    }//GEN-LAST:event_btns2MouseEntered

    private void btns2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns2MouseClicked
        fillBlankSpace1("A");
    }//GEN-LAST:event_btns2MouseClicked

    private void btns1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns1MouseExited
        backcolor (btns1, new Color(255,255,255));
    }//GEN-LAST:event_btns1MouseExited

    private void btns1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns1MouseEntered
        backcolor (btns1, new Color(153,255,153));
    }//GEN-LAST:event_btns1MouseEntered

    private void btns1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btns1MouseClicked
        fillBlankSpace1("S");
    }//GEN-LAST:event_btns1MouseClicked

    private void bs6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bs6MouseClicked
        if (hintUsed) {
            // If hint has been used, show a message
            JOptionPane.showMessageDialog(this, "You can only use hint once per level", "Hint Used", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Array representing the correct word "ABCA"
            String correctWord6 = "LIST";

            // Array of text fields
            javax.swing.JTextField[] textFields = {bnk13,bnk14,bnk15,bnk16};

            // Random object to generate random index
            java.util.Random rand = new java.util.Random();

            // Generate a random index from 0 to 3 (for 4 text fields)
            int randomIndex = rand.nextInt(2);

            // If the selected text field is empty, fill it with the correct letter
            if (textFields[randomIndex].getText().isEmpty()) {
                textFields[randomIndex].setText(String.valueOf(correctWord6.charAt(randomIndex)));
                hintUsed = true;
            }
        }
    }//GEN-LAST:event_bs6MouseClicked

    private void bt88MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt88MouseClicked
        String word = bnk13.getText()+bnk14.getText()+bnk15.getText()+bnk16.getText();

        if (word.equals("LIST")){
            JOptionPane.showMessageDialog(this, "Correct!\n Good Job!", "Result", JOptionPane.INFORMATION_MESSAGE);

            bnk13.setText("");
            bnk14.setText("");
            bnk15.setText("");
            bnk16.setText("");
           

            // switch level
            JTABPANE.setSelectedIndex(1);

        }  else {
            JOptionPane.showMessageDialog(this, "Wrong!\n Try Harder!", "Result", JOptionPane.ERROR_MESSAGE);

              bnk13.setText("");
            bnk14.setText("");
            bnk15.setText("");
            bnk16.setText("");
           
          

        }
    }//GEN-LAST:event_bt88MouseClicked

    private void bt88MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt88MouseEntered
        backcolor (bt88, new Color(153,255,153));
    }//GEN-LAST:event_bt88MouseEntered

    private void bt88MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt88MouseExited
        backcolor (bt88, new Color(255,255,255));
    }//GEN-LAST:event_bt88MouseExited

    private void b6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseClicked
        if (!bnk16.getText().isEmpty()){
            bnk16.setText(""); }
        else if (!bnk15.getText().isEmpty()){
            bnk15.setText(""); }
        else if (!bnk14.getText().isEmpty()){
            bnk14.setText(""); }
        else if (!bnk13.getText().isEmpty()){
            bnk13.setText(""); }
       
    }//GEN-LAST:event_b6MouseClicked

    private void b6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseEntered
        backcolor (b6, new Color(153,255,153));
    }//GEN-LAST:event_b6MouseEntered

    private void b6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseExited
        backcolor (b6, new Color(255,255,255));
    }//GEN-LAST:event_b6MouseExited

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void bs5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bs5MouseClicked
        if (hintUsed) {
            // If hint has been used, show a message
            JOptionPane.showMessageDialog(this, "You can only use hint once per level", "Hint Used", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Array representing the correct word "ABCA"
            String correctWord6 = "LOOP";

            // Array of text fields
            javax.swing.JTextField[] textFields = {bnk25,bnk26,bnk27,bnk28};

            // Random object to generate random index
            java.util.Random rand = new java.util.Random();

            // Generate a random index from 0 to 3 (for 4 text fields)
            int randomIndex = rand.nextInt(2);

            // If the selected text field is empty, fill it with the correct letter
            if (textFields[randomIndex].getText().isEmpty()) {
                textFields[randomIndex].setText(String.valueOf(correctWord6.charAt(randomIndex)));
                hintUsed = true;
            }
        }
    }//GEN-LAST:event_bs5MouseClicked

    private void bt89MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt89MouseClicked
        String word = bnk25.getText()+bnk26.getText()+bnk27.getText()+bnk28.getText();

        if (word.equals("LOOP")){
            JOptionPane.showMessageDialog(this, "Correct!\n Good Job!\n you completed the python", "Result", JOptionPane.INFORMATION_MESSAGE);
            bnk25.setText("");
            bnk26.setText("");
            bnk27.setText("");
            bnk28.setText("");
            

            // switch level
            JTABPANE.setSelectedIndex(1);
        }  else {
            JOptionPane.showMessageDialog(this, "Wrong!\n Try Harder!", "Result", JOptionPane.ERROR_MESSAGE);
            bnk25.setText("");
            bnk26.setText("");
            bnk27.setText("");
            bnk28.setText("");

        }
    }//GEN-LAST:event_bt89MouseClicked

    private void bt89MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt89MouseEntered
        backcolor (bt88, new Color(153,255,153));
    }//GEN-LAST:event_bt89MouseEntered

    private void bt89MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt89MouseExited
        backcolor (bt88, new Color(255,255,255));
    }//GEN-LAST:event_bt89MouseExited

    private void b5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseClicked
        if (!bnk28.getText().isEmpty()){
            bnk28.setText(""); }
        else if (!bnk27.getText().isEmpty()){
            bnk27.setText(""); }
        else if (!bnk26.getText().isEmpty()){
            bnk26.setText(""); }
        else if (!bnk25.getText().isEmpty()){
            bnk25.setText(""); }
       
    }//GEN-LAST:event_b5MouseClicked

    private void b5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseEntered
        backcolor (b5, new Color(153,255,153));
    }//GEN-LAST:event_b5MouseEntered

    private void b5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseExited
        backcolor (b5, new Color(255,255,255));
    }//GEN-LAST:event_b5MouseExited

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        choices choi = new choices();
        choi.show();

        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void bt89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt89ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt89ActionPerformed

    private void bs5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bs5MouseEntered
        changecolor(bs5, new Color(255,0,0));
    }//GEN-LAST:event_bs5MouseEntered

    private void bs5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bs5MouseExited
        changecolor(bs5, new Color(242,242,242));
    }//GEN-LAST:event_bs5MouseExited

    private void bs6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bs6MouseEntered
        changecolor(bs6, new Color(255,0,0));
    }//GEN-LAST:event_bs6MouseEntered

    private void bs6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bs6MouseExited
        changecolor(bs6, new Color(242,242,242));
    }//GEN-LAST:event_bs6MouseExited
private void fillBlankSpace3(String letter){
            if (bnk13.getText().isEmpty()){
                bnk13.setText(letter); }
            else if (bnk14.getText().isEmpty()){
                bnk14.setText(letter); }
            else if (bnk15.getText().isEmpty()){
                bnk15.setText(letter); }
            else if (bnk16.getText().isEmpty()){
                bnk16.setText(letter); }
}

private void fillBlankSpace1(String letter){
            if (bnk13.getText().isEmpty()){
                bnk13.setText(letter); }
            else if (bnk14.getText().isEmpty()){
                bnk14.setText(letter); }
            else if (bnk15.getText().isEmpty()){
                bnk15.setText(letter); }
            else if (bnk16.getText().isEmpty()){
                bnk16.setText(letter); }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTABPANE;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JTextField bnk13;
    private javax.swing.JTextField bnk14;
    private javax.swing.JTextField bnk15;
    private javax.swing.JTextField bnk16;
    private javax.swing.JTextField bnk25;
    private javax.swing.JTextField bnk26;
    private javax.swing.JTextField bnk27;
    private javax.swing.JTextField bnk28;
    private javax.swing.JLabel bs5;
    private javax.swing.JLabel bs6;
    private javax.swing.JButton bt88;
    private javax.swing.JButton bt89;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn37;
    private javax.swing.JButton btn38;
    private javax.swing.JButton btn39;
    private javax.swing.JButton btn40;
    private javax.swing.JButton btn41;
    private javax.swing.JButton btn42;
    private javax.swing.JButton btn43;
    private javax.swing.JButton btn44;
    private javax.swing.JButton btn45;
    private javax.swing.JButton btn46;
    private javax.swing.JButton btn47;
    private javax.swing.JButton btn48;
    private javax.swing.JButton btn49;
    private javax.swing.JButton btn50;
    private javax.swing.JButton btn51;
    private javax.swing.JButton btn52;
    private javax.swing.JButton btns1;
    private javax.swing.JButton btns10;
    private javax.swing.JButton btns11;
    private javax.swing.JButton btns12;
    private javax.swing.JButton btns13;
    private javax.swing.JButton btns14;
    private javax.swing.JButton btns15;
    private javax.swing.JButton btns16;
    private javax.swing.JButton btns17;
    private javax.swing.JButton btns18;
    private javax.swing.JButton btns19;
    private javax.swing.JButton btns2;
    private javax.swing.JButton btns20;
    private javax.swing.JButton btns21;
    private javax.swing.JButton btns22;
    private javax.swing.JButton btns23;
    private javax.swing.JButton btns3;
    private javax.swing.JButton btns4;
    private javax.swing.JButton btns5;
    private javax.swing.JButton btns6;
    private javax.swing.JButton btns7;
    private javax.swing.JButton btns8;
    private javax.swing.JButton btns9;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closebtn;
    private javax.swing.JPanel header;
    private javax.swing.JPanel hint;
    private javax.swing.JPanel iconbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel linehint;
    private javax.swing.JPanel linemenu;
    private javax.swing.JPanel linesetting;
    private javax.swing.JPanel max;
    private javax.swing.JPanel menu1;
    private javax.swing.JLabel mnubtn;
    private javax.swing.JPanel no2;
    private javax.swing.JPanel no4;
    private javax.swing.JPanel setting;
    // End of variables declaration//GEN-END:variables
}
