/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class start2_lvl5 extends javax.swing.JFrame {

    /**
     * Creates new form start2_lvl5
     */
    public start2_lvl5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        iconbar = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        max = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        linemenu = new javax.swing.JPanel();
        linesetting = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        setting = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        linehint = new javax.swing.JPanel();
        hint = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(51, 51, 51));
        header.setPreferredSize(new java.awt.Dimension(820, 35));
        header.setLayout(new java.awt.BorderLayout());

        iconbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(51, 51, 51));
        close.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/close (2).png"))); // NOI18N
        close.add(jLabel1, java.awt.BorderLayout.CENTER);

        iconbar.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        max.setBackground(new java.awt.Color(51, 51, 51));
        max.setLayout(new java.awt.BorderLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/maximize (2) (1).png"))); // NOI18N
        max.add(jLabel2, java.awt.BorderLayout.CENTER);

        iconbar.add(max, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        header.add(iconbar, java.awt.BorderLayout.LINE_END);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(35, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linemenu.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout linemenuLayout = new javax.swing.GroupLayout(linemenu);
        linemenu.setLayout(linemenuLayout);
        linemenuLayout.setHorizontalGroup(
            linemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        linemenuLayout.setVerticalGroup(
            linemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(linemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 3));

        linesetting.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout linesettingLayout = new javax.swing.GroupLayout(linesetting);
        linesetting.setLayout(linesettingLayout);
        linesettingLayout.setHorizontalGroup(
            linesettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        linesettingLayout.setVerticalGroup(
            linesettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(linesetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, 35, 3));

        menu.setBackground(new java.awt.Color(51, 51, 51));
        menu.setLayout(new java.awt.BorderLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/open-menu (3).png"))); // NOI18N
        menu.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 35, 40));

        setting.setBackground(new java.awt.Color(51, 51, 51));
        setting.setLayout(new java.awt.BorderLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/settings (1).png"))); // NOI18N
        setting.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 35, 40));

        linehint.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout linehintLayout = new javax.swing.GroupLayout(linehint);
        linehint.setLayout(linehintLayout);
        linehintLayout.setHorizontalGroup(
            linehintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        linehintLayout.setVerticalGroup(
            linehintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(linehint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 35, 3));

        hint.setBackground(new java.awt.Color(51, 51, 51));
        hint.setLayout(new java.awt.BorderLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconfolder/bulb (3) (1).png"))); // NOI18N
        hint.add(jLabel5, java.awt.BorderLayout.LINE_START);

        jPanel1.add(hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 35, 40));

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start2_lvl5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start2_lvl5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start2_lvl5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start2_lvl5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start2_lvl5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel close;
    private javax.swing.JPanel header;
    private javax.swing.JPanel hint;
    private javax.swing.JPanel iconbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel linehint;
    private javax.swing.JPanel linemenu;
    private javax.swing.JPanel linesetting;
    private javax.swing.JPanel max;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel setting;
    // End of variables declaration//GEN-END:variables
}
